In [2]:
import numpy as np
import MatSciPyRotations


In [3]:
stiffness=[[2.411e11, 9.69e10,1.38e11,0,0,0],
    [9.69e10,2.411e11,1.38e11,0,0,0],
    [1.38e11,1.38e11,2.4e11,0,0,0],
    [0,0,0,1.1229e11,0,0],
    [0,0,0,0,1.1229e11,0],
    [0,0,0,0,0,7.209e10]
]
stiffness=np.array(stiffness)
print(stiffness)

[[2.4110e+11 9.6900e+10 1.3800e+11 0.0000e+00 0.0000e+00 0.0000e+00]
 [9.6900e+10 2.4110e+11 1.3800e+11 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.3800e+11 1.3800e+11 2.4000e+11 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 1.1229e+11 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.1229e+11 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 7.2090e+10]]


In [4]:
from numpy import sin,cos,radians
a = radians(45)
b = radians(0)
c = radians(0)
rx = np.matrix([[1,0,0],[0,cos(a),-sin(a)],[0,sin(a),cos(a)]])
ry = np.matrix([[cos(b),0,sin(b)],[0,1,0],[-sin(b),0,cos(b)]])

rt = np.matmul(rx,ry)
MatSciPyRotations.rotate_elastic_constants(stiffness,rt)


array([[ 2.41100e+11,  1.17450e+11,  1.17450e+11, -2.05500e+10,
         0.00000e+00,  0.00000e+00],
       [ 1.17450e+11,  3.01565e+11,  7.69850e+10,  2.75000e+08,
         0.00000e+00,  0.00000e+00],
       [ 1.17450e+11,  7.69850e+10,  3.01565e+11,  2.75000e+08,
         0.00000e+00,  0.00000e+00],
       [-2.05500e+10,  2.75000e+08,  2.75000e+08,  5.12750e+10,
         0.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         9.21900e+10, -2.01000e+10],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -2.01000e+10,  9.21900e+10]])

In [5]:
rt = np.matmul(ry,rx)

MatSciPyRotations.rotate_elastic_constants(stiffness,rt)


array([[ 2.41100e+11,  1.17450e+11,  1.17450e+11, -2.05500e+10,
         0.00000e+00,  0.00000e+00],
       [ 1.17450e+11,  3.01565e+11,  7.69850e+10,  2.75000e+08,
         0.00000e+00,  0.00000e+00],
       [ 1.17450e+11,  7.69850e+10,  3.01565e+11,  2.75000e+08,
         0.00000e+00,  0.00000e+00],
       [-2.05500e+10,  2.75000e+08,  2.75000e+08,  5.12750e+10,
         0.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         9.21900e+10, -2.01000e+10],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -2.01000e+10,  9.21900e+10]])