In [234]:
using Revise
using LinearAlgebra
using Rotations

include("EFITModule/EFIT.jl")


Main.EFIT

In [235]:
c = Matrix(Main.EFIT.AnisoMats["X6CrNi1811"].c)
r = RotXYZ(0,45,0)

3×3 RotXYZ{Float64} with indices SOneTo(3)×SOneTo(3)(0.0, 45.0, 0.0):
  0.525322  -0.0   0.850904
  0.0        1.0  -0.0
 -0.850904   0.0   0.525322

In [239]:
Tσ = [
    r[1,1]^2 r[2,1]^2 r[3,1]^2 2*r[1,1]*r[2,1] 2*r[2,1]*r[3,1] 2*r[3,1]*r[1,1];
    r[1,2]^2 r[2,2]^2 r[3,2]^2 2*r[1,2]*r[2,2] 2*r[2,2]*r[3,2] 2*r[3,2]*r[1,2];
    r[1,3]^2 r[2,3]^2 r[3,3]^2 2*r[1,3]*r[2,3] 2*r[2,3]*r[3,3] 2*r[3,3]*r[1,3];
    r[1,1]*r[1,2] r[2,1]*r[2,2] r[3,1]*r[3,2] r[1,1]*r[2,2]+r[1,2]*r[2,1] r[2,1]*r[3,2] + r[3,1]*r[2,2] r[3,1]*r[1,2]+r[3,2]*r[1,1];
    r[1,2]*r[1,3] r[2,2]*r[2,3] r[3,3]*r[3,2] r[2,3]*r[1,2]+r[1,3]*r[2,2] r[2,2]*r[3,3] + r[3,2]*r[2,3] r[3,2]*r[1,3]+r[1,2]*r[3,3];
    r[1,1]*r[1,3] r[2,3]*r[2,1] r[3,3]*r[3,1] r[1,3]*r[2,1]+r[1,1]*r[2,3] r[2,3]*r[3,1] + r[2,1]*r[3,3] r[3,3]*r[1,1]+r[3,1]*r[1,3]]

T = [
    r[1,1]^2 r[2,1]^2 r[3,1]^2 2*r[2,1]*r[3,1] 2*r[1,1]*r[3,1] 2*r[1,1]*r[2,1];
    r[1,2]^2 r[2,2]^2 r[3,2]^2 2*r[2,2]*r[3,2] 2*r[1,2]*r[3,2] 2*r[1,2]*r[2,2];
    r[1,3]^2 r[2,3]^2 r[3,3]^2 2*r[2,3]*r[3,3] 2*r[1,3]*r[3,3] 2*r[1,3]*r[2,3];
    r[1,2]*r[1,3] r[2,2]*r[2,3] r[3,2]*r[3,3] r[2,2]*r[3,3]+r[2,3]*r[3,2] r[3,2]*r[1,3] + r[3,3]*r[1,2] r[2,2]*r[1,3]+r[2,3]*r[1,2];
    r[1,3]*r[1,1] r[2,3]*r[2,1] r[3,3]*r[3,1] r[2,3]*r[3,1]+r[1,2]*r[3,3] r[3,3]*r[1,1] + r[1,3]*r[3,1] r[2,3]*r[1,1]+r[2,1]*r[1,3];
    r[1,1]*r[1,2] r[2,1]*r[2,2] r[3,1]*r[3,2] r[2,1]*r[3,2]+r[2,2]*r[3,1] r[3,1]*r[1,2] + r[3,2]*r[1,1] r[2,1]*r[2,1]+r[2,2]*r[1,1]]

M = [
    r[1,1]^2 r[1,2]^2 r[1,3]^2 2*r[1,1]*r[1,2] 2*r[1,2]*r[1,3] 2*r[1,3]*r[1,1];
    r[2,1]^2 r[2,2]^2 r[2,3]^2 2*r[2,1]*r[2,2] 2*r[2,2]*r[2,3] 2*r[2,3]*r[2,1];
    r[3,1]^2 r[3,2]^2 r[3,3]^2 2*r[3,1]*r[3,2] 2*r[3,2]*r[3,3] 2*r[3,3]*r[3,1];
    r[1,1]*r[2,1] r[1,2]*r[2,2] r[1,3]*r[2,3] r[1,1]*r[2,2]+r[2,1]*r[1,2] r[1,2]*r[2,3] + r[1,3]*r[2,2] r[1,3]*r[2,1]+r[2,3]*r[1,1];
    r[2,1]*r[3,1] r[2,2]*r[3,2] r[3,3]*r[2,3] r[3,2]*r[2,1]+r[3,1]*r[2,2] r[2,2]*r[3,3] + r[2,3]*r[3,2] r[2,3]*r[3,1]+r[2,1]*r[3,3];
    r[1,1]*r[3,1] r[3,2]*r[1,2] r[3,3]*r[1,3] r[3,1]*r[1,2]+r[1,1]*r[3,2] r[3,2]*r[1,3] + r[1,2]*r[3,3] r[3,3]*r[1,1]+r[1,3]*r[3,1]]


Tϵ=zeros(6,6)
Tϵ[:,:] .= Tσ[:,:]
Tϵ[4:6,1:3] .= Tϵ[4:6,1:3].*2 
Tϵ[1:3,4:6] .= Tϵ[1:3,4:6]./2 

T[4:6,1:3] .= T[4:6,1:3].*sqrt(2)
T[1:3,4:6] .= T[1:3,4:6]./sqrt(2)


cPrime = T*c*inv(T)

for m in (c, cPrime)
    eigs = eigvals(m)
    I1 = eigs[1]+eigs[2]+eigs[3]
    I2 = eigs[1]*eigs[2]+eigs[1]*eigs[3]+eigs[2]*eigs[3]
    display(m)
    println("I1: $I1, I2: $I2")
end

6×6 Matrix{Float32}:
 2.411f11  9.69f10   1.38f11  0.0        0.0        0.0
 9.69f10   2.411f11  1.38f11  0.0        0.0        0.0
 1.38f11   1.38f11   2.4f11   0.0        0.0        0.0
 0.0       0.0       0.0      1.1229f11  0.0        0.0
 0.0       0.0       0.0      0.0        1.1229f11  0.0
 0.0       0.0       0.0      0.0        0.0        7.209f10

I1: 2.7216124e11, I2: 2.428009e22


6×6 Matrix{Float64}:
 2.44196e11   1.26658e11   1.34108e11   0.0          3.10654e9    0.0
 1.26658e11   2.411e11     1.08242e11   0.0         -2.59814e10   0.0
 1.34108e11   1.08242e11   2.44689e11   0.0         -2.41118e9    0.0
 0.0          0.0          0.0          8.31837e10   0.0         -1.79693e10
 3.10654e9   -2.59814e10  -2.41118e9    0.0          1.04505e11   0.0
 0.0          0.0          0.0         -1.79693e10   0.0          1.01196e11

I1: 2.7216120513363528e11, I2: 2.4280084803061027e22


In [246]:
rT = RotXYZ(0,0,1)
cPrime=Main.EFIT.rotMatrix(c,rT,checkEigen=true)



6×6 Matrix{Float64}:
 2.27908e11   1.10092e11  1.38e11      8.53816e9   0.0         0.0
 1.10092e11   2.27908e11  1.38e11     -8.53816e9   0.0         0.0
 1.38e11      1.38e11     2.4e11       3.09433e-6  0.0         0.0
 8.53816e9   -8.53816e9   3.03204e-6   1.38674e11  0.0         0.0
 0.0          0.0         0.0          0.0         8.38254e10  1.82769e10
 0.0          0.0         0.0          0.0         1.82769e10  1.00555e11

In [50]:
c = Main.EFIT.AnisoMats["X6CrNi1811"].c
mats = Array{Matrix{Float32},1}()
angles = Array{Tuple{Float64, Float64, Float64},1}()
for i in 1:50000
    rx = rand(Float32)*180.0
    ry = rand(Float32)*180.0
    rz = rand(Float32)*180.0
    push!(angles, (rx,ry,rz))
    push!(mats, Main.EFIT.rotateMatrix(c,rx,ry,rz))
end

In [51]:
catches = Array{Integer,1}()
Threads.@threads for i in 1:size(mats,1)
    try
        inv(mats[i])
    catch
        push!(catches, i)
    end
end

In [52]:
angles[catches]


23-element Vector{Tuple{Float64, Float64, Float64}}:
 (90.54372668266296, 87.14104413986206, 119.22342896461487)
 (90.38443565368652, 84.28420186042786, 166.7468512058258)
 (90.29054760932922, 65.08419871330261, 110.51852345466614)
 (89.72917199134827, 73.9897871017456, 121.71463251113892)
 (90.22952198982239, 112.48331665992737, 34.91549491882324)
 (90.13667464256287, 73.84295225143433, 114.62920188903809)
 (90.41345715522766, 97.91372895240784, 38.688472509384155)
 (89.98839139938354, 90.40583968162537, 24.687073230743408)
 (89.62373971939087, 111.13664388656616, 113.12165021896362)
 (89.70170617103577, 77.82242774963379, 111.23518824577332)
 (89.44802284240723, 92.47496008872986, 119.19710040092468)
 (89.69516158103943, 93.2030189037323, 13.485814332962036)
 (89.58866715431213, 92.12268948554993, 140.73121547698975)
 (89.67271685600281, 74.25478935241699, 148.45078468322754)
 (89.70263957977295, 108.07822823524475, 119.42710518836975)
 (90.43022632598877, 103.22080135345459, 41.7403

In [45]:
for (k,p) in d
    if p > 4
        println(angles[k])
    end
end

(90.12759804725647, 59.16380167007446, 44.25833702087402)
(89.622323513031, 82.59690999984741, 35.62049746513367)


In [46]:
angles[3721]

(55.20098805427551, 92.19023823738098, 112.31265306472778)